name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Install SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.172.226.78
          username: vm-modul4
          key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Cek folder project"
            if [ ! -d "/home/seniorproject-rabu/senpro/463601/modul01/senpro-github-action/" ]; then
              echo "Repository belum di-clone. Cloning..."
              mkdir -p ~/senpro/463601/modul01
              cd ~/senpro/463601/modul01
              git clone https://github.com/hervibest/senpro-github-action.git
              cd ~/senpro/463601/modul01/senpro-github-action/
              echo "Install Package dan Build Project"
              npm install
              npm run build
            else
              echo "Repository sudah ada. Building..."
              cd ~/senpro/463601/modul01/senpro-github-action/
              git restore
              git pull origin main
              echo "Install Package dan Build Project"
              npm install
              npm run build
            fi