name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Set up SSH environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PASSPHRASE }}" > ~/.ssh/passphrase
          chmod 600 ~/.ssh/passphrase

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 20.172.226.78
          username: vm-modul4
          key_path: ~/.ssh/id_rsa
          passphrase_path: ~/.ssh/passphrase
          script: |
            cd /path/to/remote/directory
            # Command to deploy the application (e.g., copying files, restarting services, etc.