name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 20.172.226.78
          username: vm-modul4
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/remote/directory
            # Command to deploy the application (e.g., copying files, restarting services, etc.)