name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH environment
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ssh-modul4.pem
          chmod 600 ~/.ssh/ssh-modul4.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/ssh-modul4.pem

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/ssh-modul4.pem vm-modul4@20.172.226.78 "cd /path/to/remote/directory && <command-to-deploy>"
